### ISSUE TITLE
Add logger::log_shiny_input_changes once it allows to log to a custom namespace

### ISSUE THREAD

**Issue by kpagacz** [insightsengineering/teal.modules.general#239]
The current, latest version of logger does not allow logging log_shiny_input_changes to a custom namespace.

We have a couple of options:
* create our own function logging changes in shiny input (not that hard, just copy logger's with small additions)
* wait for logger to get updated. I have opened a PR into logger with the requested functionality but I cannot be sure when it will get merged. https://github.com/daroczig/logger/pull/93

The objective of the issue is to add the functionality (either our own or logger's) to log changes in shiny inputs. Make sure to exclude sensitive shiny inputs.

**Comment by donyunardi** [comment]
The PR that @kpagacz created already merged so this issue is no longer a blocker. 
I did play around with this:

![image](https://github.com/insightsengineering/teal.modules.general/assets/8597300/3be01239-c0ce-4e73-b4f6-d60ec5fcb917)

We can pick this up after the ddl refactor.

**Comment by donyunardi** [comment]
Note: In the example above, I was adding the log at the `teal` level, not the module.

**Comment by pawelru** [comment]
@donyunardi the PR is there on master but I am not too sure if this got released on CRAN. We should use CRAN only dependencies. This guy is not tagging on his repo so it's hard to check it from there. Using github.com/cran/logger I double checked that the latest release (which is 2 years old btw) [**does not include**](https://github.com/cran/logger/blob/master/R/hooks.R#L121) the fix.

**Comment by m7pr** [comment]
`logger` wasn't released still. it's 820 days already https://github.com/daroczig/logger/pull/93#issuecomment-1971116424

**Comment by m7pr** [comment]
After a ping he decided to do a release at the end of this week. https://github.com/daroczig/logger/issues/144

**Comment by pawelru** [comment]
hey @m7pr I noticed you have done it for modules only. I think we are also interested in covering the "core" as well - `teal`, `teal.slice` and others if applicable. Otherwise this feels to be incomplete.

**Comment by m7pr** [comment]
yeah, the scope was ambiguous. thanks for the clarification
