### ISSUE TITLE
scatterplot: Bad error message when row facet and column facet are the same variable

### ISSUE THREAD

**Issue by denisovan31415** [insightsengineering/teal.modules.general#376]
![Screen Shot 2022-04-07 at 1 39 17 PM](https://user-images.githubusercontent.com/12874196/162273983-0fc88dd4-3b6f-451c-b827-3c74f93e4095.png)

**Comment by donyunardi** [comment]
### Acceptance Criteria: 
Provide a more user-friendly error message

**Comment by BLAZEWIM** [comment]
yes, thanks for noticing
