### ISSUE TITLE
Replace chunks with the quosure

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.modules.general#388]
Introduce Quosure in tmg.
- Please work on the feature branch related to this 26_new_chunks@main
- Assign to this issue https://github.com/insightsengineering/teal.modules.general/issues/402 and address both in the same PR as they need to be resolved in the same time (because merge_expression_module needs data)

**Comment by Polkas** [comment]
- [ ] tm_a_pca
- [ ] tm_a_regression
- [ ] tm_data_table
- [ ] tm_file_viewer
- [ ] tm_front_page
- [ ] tm_g_association
- [ ] tm_g_bivariate
- [ ] tm_g_distribution
- [ ] tm_g_response
- [ ] tm_g_scatterplot
- [ ] tm_g_scatterplotmatrix
- [ ] tm_missing_data
- [ ] tm_outliers
- [ ] tm_t_crosstable
- [ ] tm_variable_browser
