### ISSUE TITLE
Unhelpful title in tm_g_association

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.modules.general#399]
From https://github.com/insightsengineering/coredev-tasks/issues/242
![image](https://user-images.githubusercontent.com/15201933/171388829-792d72c0-138b-4b0a-b0da-e9cf8e3b34b9.png)

**Comment by chlebowa** [comment]
When I try firing up the example application I get this:

![Image](https://user-images.githubusercontent.com/114988527/200282201-d67acef7-cf52-4440-b0bf-69bb9159d101.PNG)

Seems to me like it might be connected to the recent refactor. There are other issues downstream as well, e.g. no function called `get_join_keys`.


The issue itself seems to have already been taken care of with [this line](https://github.com/insightsengineering/teal.modules.general/blob/main/R/tm_g_association.R#L368).

**Comment by gogonzo** [comment]
@chlebowa I couldn't reproduce this. It looks like the environment issue. Probably, current `teal@main` is missing in your local env. Please install again and confirm if the error still occurs

**Comment by chlebowa** [comment]
@gogonzo Indeed.
