### ISSUE TITLE
R CMD check --as-cran result: Address Warnings and Note

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.modules.general#453]
* Fix URLs
* Update Title field in DESCRIPTION file

![image](https://user-images.githubusercontent.com/8597300/188729144-97dace2e-7623-49c1-a87a-d337dcf64f52.png)

**Comment by nikolas-burkoff** [comment]
Note there is also:

![image](https://user-images.githubusercontent.com/15201933/189346475-fa6745da-667c-48b2-8669-3bb0aaab606e.png)
![image](https://user-images.githubusercontent.com/15201933/189346525-65a2d838-968c-430e-b933-036d8a57c86c.png)
![image](https://user-images.githubusercontent.com/15201933/189346542-f00380cb-0ab6-4bfd-9fcc-e5be050f40e7.png)

- No idea about what to do with the first one @Polkas does that matter for CRAN submission?
- the second and third ones are easy
- the datatable example can be simplified by not constantly calling scda to reload the data (both in the examples and in the `CdiscTealData$check()`

**Comment by Polkas** [comment]
Regarding Imports/Depends Note ... 
Till we run on the package on win-builder not sure if this  still matter.
Another thing is that we should do what is recommended and use requireNamespace to try to load a package and if not there ask to install it for this specific functionality.
