### ISSUE TITLE
tm_missing_data reporting issues

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.modules.general#471]
From https://github.com/insightsengineering/teal.modules.general/issues/469

-  ~~The report card doesn't actually say what dataset is being considered - maybe this extra line could be added in~~

- Is this what we want? Especially because when we reorder the table on-screen - it does not take the reorder into account when adding the tibble to the report card (should it?)

![image](https://user-images.githubusercontent.com/15201933/193824868-e1b74b28-2a8f-44f0-b816-c808ba56413f.png)

**Comment by mhallal1** [comment]
The first point is a one liner fix, the second point is probably because the table is a `DT` table, adopt `table_with_settings` maybe?

**Comment by kumamiao** [comment]
If the first point is a one liner fix, would be great to go ahead and address it in the UAT if feasible. I'm okay with putting the second into the backlog if it's not that straightforward to fix.

**Comment by donyunardi** [comment]
For the first issue, I'm fine with pushing the fix during UAT if the risk is minimal.

Are we thinking about updating the card name and the content, or just the content?
@kumamiao can you give an input on how we should mention the dataset name? Would it be the same line with the title or should it be a new line, etc?

**Comment by nikolas-burkoff** [comment]
Moving second item to backlog

**Comment by chlebowa** [comment]
Acceptance criteria:
Ensure the table in the report reflects the state of the table in the app, including user-directed sorting.
Make sure to include sorting by missing values.

**Comment by donyunardi** [comment]
As discussed with @kumamiao, we don't need to have the report reflects the user-directed sorting.
Closing.
