### ISSUE TITLE
[Reporter] Variable browser: missing table in report

### ISSUE THREAD

**Issue by BLAZEWIM** [insightsengineering/teal.modules.general#477]
1. Go to any app with Variable Browser, to Variable Browser module, add any card to report
https://rsconnect.roche.com/NEST/main/early-dev/
2. Table is missing in report, shouldn't it be there?

**Comment by donyunardi** [comment]
If you're referring to the table on the left side (with the datasets variable), then I think this is the default behavior.
The table is not included, only the visualization when the variable is selected.

@nikolas-burkoff @mhallal1 do you agree with this?

**Comment by mhallal1** [comment]
@donyunardi Exactly as Dony explained, this is default behaviour and we do not expect to include the table of variables. Therefore, i am closing this issue.
