### ISSUE TITLE
[Bug]: QQplot not displayed

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.modules.general#503]
### What happened?

QQplot is not displayed in `tm_g_distribution`.
![image](https://user-images.githubusercontent.com/114988527/209539969-665b9d20-063e-4650-8776-ddefc7dddc70.png)

Console says:
```
Warning: Computation failed in `stat_qq()`
Caused by error in `distribution()`:
! could not find function "distribution"
Warning: Computation failed in `stat_qq_line()`
Caused by error in `distribution()`:
! could not find function "distribution"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by mhallal1** [comment]
fixed by https://github.com/insightsengineering/teal.modules.general/pull/502
