### ISSUE TITLE
fix lint check notice on teal.modules.general

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal.modules.general#536]
### Several lint notices have been observed that can be resolved with minor changes. I have mentioned a few examples below.

Check notice e.g 
![image](https://github.com/insightsengineering/teal.modules.general/assets/6700955/db37eca6-86cf-4523-920d-b63683b53f44)
- "multiple" is wordy or unneeded
- "validate" is wordy or unneeded

![image](https://github.com/insightsengineering/teal.modules.general/assets/6700955/7dbe8f60-477f-4753-b0f3-800d2c022e75)
- "only" can weaken meaning
> "This plot can only have one regressor." can be change to 
> "This plot can have only one regressor."

- "silently" can weaken meaning

**Comment by pawelru** [comment]
This was not lint but rather a grammar checks. There were much more errors like these and we have decided to remove it completely without a fix.
