### ISSUE TITLE
tm_data_table filter applys for all dataset

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal.modules.general#542]
I wanted confirm if its by design ?

The `tm_data_table` module from `teal.modules.general `package allows users to specify multiple datasets and  the "Add Filter Variables" section allow user to select filter. When using this module, the `ADSL` dataset will show all of its columns, while the `ADRS` dataset will only display columns that are not common with `ADSL`. and e.g  if I choose `"Country" ` for filtering it will filter both dataset based on selection though filter is present only in ADSL filtering widget.
SAMPLE app
```
ADSL <- teal.modules.general::rADSL
ADRS <- teal.modules.general::rADRS
app <- teal::init(
  data = teal.data::cdisc_data(
    teal.data::cdisc_dataset("ADSL", ADSL, code = "ADSL <- teal.modules.general::rADSL"),
    teal.data::cdisc_dataset("ADRS", ADRS, code = "ADRS <- teal.modules.general::rADRS"),
    check = TRUE
  ),
  modules = teal::modules(
    teal.modules.general::tm_data_table(
      variables_selected = list(ADSL = c("STUDYID", "USUBJID", "SUBJID", "SITEID", "AGE", "SEX")),
      dt_args = list(caption = "ADSL Table Caption")
    )
  )
)
if (interactive()) {
  shinyApp(app$ui, app$server)
}
```
![image](https://github.com/insightsengineering/teal.modules.general/assets/6700955/d83a59fc-e177-4eda-ba75-e5bdda096766)

**Comment by chlebowa** [comment]
Child data sets are filtered along with their parents.

**Comment by kartikeyakirar** [comment]
thanks! understood.
