### ISSUE TITLE
[Bug]: `tm_variable_browser` plots disappear when maximized

### ISSUE THREAD

**Issue by anajens** [insightsengineering/teal.modules.general#547]
### What happened?

When clicking the button the maximize the plot, only an empty screen is shown:

(1) 
![Screen Shot 2023-08-02 at 10 17 14 AM](https://github.com/insightsengineering/teal.modules.general/assets/43623360/de168c9d-e8c2-4b8f-a6b8-6f52dee6a16e)

(2)
![image](https://github.com/insightsengineering/teal.modules.general/assets/43623360/ab8095b3-1e42-4814-bbec-3e3c3edc7920)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by kartikeyakirar** [comment]
I am attaching a bug here, which I discovered in the `teal.widgets` call from `tm_variable_browse`r. The issue can be found at the following link: https://github.com/insightsengineering/teal.widgets/issues/171
