### ISSUE TITLE
[Bug]: Flash Error Arises in tm_missing_data Upon Changing tabs

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal.modules.general#550]
### What happened?

This issue is linked to the problem described in the issue: https://github.com/insightsengineering/teal.modules.general/issues/548

When a dataset is chosen and tab changes occur, an initial error is displayed, followed by successful loading of the plot.

https://github.com/insightsengineering/teal.modules.general/assets/6700955/338881de-ac7c-489a-a87f-2d92d2512fcf

**Comment by chlebowa** [comment]
Please check if this persists after [this PR](https://github.com/insightsengineering/teal.modules.general/pull/553).

**Comment by kartikeyakirar** [comment]
this issue is no longer reproducible.
