### ISSUE TITLE
[Bug]: qqplot does not generate in tm_g_distribution

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal.modules.general#551]
### What happened?

In the exploratory app, there is a bug where the QQplot does not generate in the Distribution tab, and instead, it throws an error on the screen.

Steps to Reproduce:

- Go to the exploratory app: https://genentech.shinyapps.io/nest_exploratory_main/
- Select the Distribution tab.
- Attempt to select QQplot, resulting in the error.

![image](https://github.com/insightsengineering/teal.modules.general/assets/6700955/5541ec8d-e028-4f0b-9dbb-e474aa6de149)

**Comment by gogonzo** [comment]
Fixed by https://github.com/insightsengineering/teal.modules.general/pull/553
