### ISSUE TITLE
[Bug]: Error caught on screen `Call execution failed:`

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal.modules.general#567]
### What happened?

A bug happened!

In [exploratory](https://genentech.shinyapps.io/NEST_exploratory_main/) app, an attempt to produce a table along with the "`active variable summary`" in the tm_data_table module has resulted in failure. with an error message on the screen.

Error Details:
The error originates from the filtering process within the `ADLBPCA `dataset, particularly concerning the `IGA-Baseline` column. 

Steps to reproduce:

- open [exploratory](https://genentech.shinyapps.io/NEST_exploratory_main/) app
- Go to DataTable tab
- In `ADLBPCA` dataset select `IGA-Baseline` 
- move slider

Screenshot
<img width="1552" alt="Screenshot 2023-08-10 at 3 58 42 PM" src="https://github.com/insightsengineering/teal.modules.general/assets/6700955/95385708-6bb6-41b9-ab1a-8b08be695d69">

**Comment by kartikeyakirar** [comment]
The error encountered here is likely due to non-standard evaluation (NSE) in `dplyr::filter` when referring to columns with spaces or special characters.

**Comment by chlebowa** [comment]
How did a syntactically invalid column name get in there in the first place? Was `IGA-Baseline` created by the app dev? Was it in the original data? Do we not run `make.names` anywhere?

**Comment by kartikeyakirar** [comment]
@chlebowa 

The `ADLBPCA ` dataset is generated using the `pivot_wider` function, which maps column values to column names, leading to the presence of syntactically invalid column names. [code ref](https://github.com/insightsengineering/teal.gallery/blob/5816df5f41e7d2f1124807b5884d65f2315add31/exploratory/app.R#L49).

The following code excerpt demonstrates the creation of the ADLBPCA dataset:

```
ADLBPCA <- ADLB %>%
  dplyr::select(USUBJID, STUDYID, SEX, ARMCD, AVAL, AVISIT, PARAMCD) %>%
  tidyr::pivot_wider(
    values_from = "AVAL",
    names_from = c("PARAMCD", "AVISIT"),
    names_sep = " - "
  )
```
The column name "IGL - BASLINE" is a result of combining the "PARAMCD" and "AVISIT" columns. Notably, there is no instance of a make.name call in the code.

**Comment by averissimo** [comment]
Any change to that code probably needs an equivalent modification on the [user guide](https://github.com/insightsengineering/user-guide/blob/477b72fbae1b172fbde30e89d5c0704ed80301f7/content/teal/sample_apps/sample-app-exploratory.md?plain=1#L43)

There seem to be no more instances of this `names_sep` being used anywhere else in insightsengineering org, at least with spaces.

Q: Does this reveal a possible bug/new feature for generating the filter call? Or is it a design decision to not support these column names?

**Comment by chlebowa** [comment]
No, I got this.
