### ISSUE TITLE
[Question]: is `ggplot2::theme_test()`  a real `theme`?

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.modules.general#635]
We do allow to pass various `{ggplot2}` themes in our encoding panel, for example in `tm_missing_data`
<img width="254" alt="image" src="https://github.com/insightsengineering/teal.modules.general/assets/133694481/d624974b-d898-4776-898d-47be379f972a">

Is this theme really o ggplot2 theme that is meaningful?
`?ggplot2::theme_test` states

> A theme for visual unit tests

**Comment by chlebowa** [comment]
I guess we can drop it.

**Comment by m7pr** [comment]
If we are about to drop it, then we should change the set of possible parameters of ggplot_args in multiple modules. This just looks like some kind of a remaining from the prototyping phase

**Comment by chlebowa** [comment]
What do you mean?

**Comment by m7pr** [comment]
I meant that we should limit `ggtheme` parameter in all modules in this package, so they do not allow `test` to be used

**Comment by chlebowa** [comment]
Care to have a look at the PR?

**Comment by m7pr** [comment]
oh sorry, totally missed the PR. will take a look
