### ISSUE TITLE
Pre-release activities - Potential removal of dependencies

### ISSUE THREAD

**Issue by averissimo** [insightsengineering/teal.modules.general#643]
Part of #624 related to vignettes. Please make a PR to `pre-release@main`

Consider:

- [x] Removal of `{magrittr}` by importing pipe operator from `{dplyr}`   :heavy_check_mark: _done_
- [x] Other packages that can be easily removed   :heavy_check_mark: removed `tidyselect` as its functions are reexported from `dplyr`
- Move any of the packages from `Depends` -> `Imports`
  - [x] `{ggmosaic}`   :x: _impossible_ (see below)
  - [x] `{ggplot2}`   :x: _impossible_ (see below)
  - [x] `{shinyTree}`   :heavy_check_mark: _done_
  - [x] `{teal.transform}`   :x: _valid_: `teal.transform` functions should be available to `tmg` users
  - [x] `{teal}`   :x: _valid_: `teal` dependency is standard in all module packages
  - [x] `{shiny}`   :x: _valid_: like `teal`, module packages use `shiny` extensively

**Comment by chlebowa** [comment]
`ggmosaic` must stay in `Depends` as per this note in `teal.modules.general.R`:
```
# nolint start
# Note ggmosaic (version <= 0.3.3) needs to be in DEPENDS as the following does not work if it is imported
# df <- data.frame(x = c("A", "B", "C", "A"), y = c("Z", "Z", "W", "W"))
# ggplot(df) + ggmosaic::geom_mosaic(aes(x = ggmosaic::product(x), fill = y))
# nolint end
```

I experimented with moving it to `Imports` and it seems to be valid.

`ggplot2` will remain in `Depends` as well as long as `ggmosaic` has to. It makes no sense to me to have a basic funcitonality in `Imports` and an enhancement in `Depends`.

**Comment by chlebowa** [comment]
I would actually consider adding `@import stats` as there are numerous uses of multiple functions. Not necessarily, though, prefixes do add clarity.

The same goes for `teal.widgets`.

**Comment by chlebowa** [comment]
`nestcolor` is used in most (if not all) examples but nowhere else. I believe it should be upgraded from `Suggests` to `Imports` because we don't want those examples to be made conditional.
Alternatively, we can use `require(nestcolors)` rather than `library(nestcolors)` in examples.

Thoughts?

**Comment by chlebowa** [comment]
`teal.data` should be upgraded from `Suggests` to `Imports` as `datanames` and `join_keys` is used in many modules, aside from examples.

**Comment by chlebowa** [comment]
done

**Comment by pawelru** [comment]
Can you please check if this solves https://github.com/insightsengineering/teal.modules.general/issues/625

**Comment by chlebowa** [comment]
Yes, I got no notes on my last pass.
![image](https://github.com/insightsengineering/teal.modules.general/assets/114988527/78f68dfe-8055-4252-9897-d98a0ccc73a2)
