### ISSUE TITLE
[Bug]: Checkbox with label "Treat Variable as Factor" doesn't update

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal.modules.general#682]
### What happened?

The dynamic behavior of the checkbox is not working as intended. The checkbox should be checked or unchecked based on the condition `unique_entries < 6`. However, it seems that the issue is caused by the condition `is.null(isolate(input$numeric_as_factor))` always being evaluated as FALSE after the initial assignment.

Check `mtcars$cyl (<6)`and` mtcars$hp (<30)`

sample code
```
library(teal.widgets)

# Module specification used in apps below
tm_variable_browser_module <- tm_variable_browser(
  label = "Variable browser",
  ggplot2_args = ggplot2_args(
    labs = list(subtitle = "Plot generated by Variable Browser Module")
  )
)

# general data example
data <- teal_data()
data <- within(data, {
  iris <- iris
  mtcars <- mtcars
  women <- women
  faithful <- faithful
  CO2 <- CO2
})
datanames(data) <- c("iris", "mtcars", "women", "faithful", "CO2")

app <- init(
  data = data,
  modules = modules(tm_variable_browser_module)
)
if (interactive()) {
  shinyApp(app$ui, app$server)
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by vedhav** [comment]
Changing the default value over [here](https://github.com/insightsengineering/teal.modules.general/blob/4faa5055bed7147191e09a7838070f84ffd3dde3/R/tm_variable_browser.R#L363-L367) to this should fix this:
```r
value = unique_entries < .unique_records_default_as_factor
```

**Comment by kartikeyakirar** [comment]
> Feature: By default if there are < 6 distinct values it should be converted into a factor. However, if the user decides to keep the checkbox on/off for a given column, it should remain the same and not change.

So here are two options

**Simple Fix:** Update the checkbox every time a user selects a row from the DT table. This will check the condition `unique_entries < .unique_records_default_as_factor` and update the checkbox accordingly.

`Complex Approach:` Implement a mechanism to store information about user selections on the checkbox for each column. If a user makes any changes after the default selection, the mechanism should retain that selection.
