### ISSUE TITLE
[Question]: Should  `ggplot2_args` for caption or subtitle be applied to all plots in `tm_g_association`

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.modules.general#769]
Consider following code

<details><summary> app code </summary>

```r
data <- teal_data()
data <- within(data, {
  require(nestcolor)
  ADSL <- rADSL
})
datanames(data) <- "ADSL"
join_keys(data) <- default_cdisc_join_keys[datanames(data)]


app <- init(
  data = data,
  modules = modules(
    tm_g_association(
      ref = data_extract_spec(
        dataname = "ADSL",
        select = select_spec(
          label = "Select variable:",
          choices = variable_choices(
            data[["ADSL"]],
            c("SEX", "RACE", "COUNTRY", "ARM", "STRATA1", "STRATA2", "ITTFL", "BMRKR2")
          ),
          selected = "RACE",
          fixed = FALSE
        )
      ),
      vars = data_extract_spec(
        dataname = "ADSL",
        select = select_spec(
          label = "Select variables:",
          choices = variable_choices(
            data[["ADSL"]],
            c("SEX", "RACE", "COUNTRY", "ARM", "STRATA1", "STRATA2", "ITTFL", "BMRKR2")
          ),
          selected = "BMRKR2",
          multiple = TRUE,
          fixed = FALSE
        )
      ),
      ggplot2_args = ggplot2_args(
        labs = list(subtitle = "Plot generated by Association Module",
                    caption = "NEST PROJECT")
      )
    )
  )
)
if (interactive()) {
  shinyApp(app$ui, app$server)
}
```

</details>

Should `ggplot2_args` be added to all plots

```r
  ggplot2_args = ggplot2_args(
    labs = list(subtitle = "Plot generated by Association Module",
                caption = "NEST PROJECT")
  )
```

In this plot I think it would be beneficial if some are applied to the top plot, and other args (like `caption`) to be applied to the second plot

<img width="343" alt="image" src="https://github.com/user-attachments/assets/a03743cf-1d9b-430c-a88f-5d9cb716caa5">

This is super weird for `exploratory` teal.gallery app, where `ggplot2_args` are passed as a `teal` option
https://github.com/insightsengineering/teal.gallery/blob/main/exploratory/app.R#L2C1-L5C2

which produces multiple plots with multiple captions, that just take space!

<img width="509" alt="image" src="https://github.com/user-attachments/assets/fb14e0be-cd0f-45d4-8cc0-92d4d88b0869">

**Comment by gogonzo** [comment]
@m7pr `ggplot2_args` can be provided as list. Please check `tm_g_association(ggplot2_args)` documentation. If you instead specify `ggplot2_args = list(Bivariate2 = ggplot2_args(...))`, then it will be applied to the second graph only. Problem you're highlighting is "not universal default values" and alternative isn't that easy. I agree it is not nice to produce multiple footnotes for each graph, but because we are using `options()` for "default_ggplot2_args" it is easier to set single option for the whole package. Otherwise each `tm_` function will have to set own defaults.

**Comment by m7pr** [comment]
Thanks, makes sense. I was unaware of if. I think we can live with it, knowing it can be improved if we extend the code of `teal.gallery` apps. So not necessarily a question anymore
