### ISSUE TITLE
Fix failed pipeline

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.modules.general#771]
https://github.com/pawelru/ie_status?tab=readme-ov-file

**Comment by m7pr** [comment]
Since https://github.com/insightsengineering/verdepcheck/pull/56 verdepcheck issue got fixed and merged I started new pipeline https://github.com/insightsengineering/teal.modules.general/actions/runs/10632654070

**Comment by m7pr** [comment]
Restarting:
- r-hub https://github.com/insightsengineering/teal.modules.general/actions/runs/11162750664
- revdepcheck https://github.com/insightsengineering/teal.modules.general/actions/runs/11162755960
