### ISSUE TITLE
[Bug]: Add magritrr and ggplot2 to imports

### ISSUE THREAD

**Issue by svalvaro** [insightsengineering/teal.modules.general#785]
### What happened?

Functions from these two packages are being imported, we need to add them to the DESCRIPTION --> Imports.
`ggplot2` and `magrittr`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
Duplicate of #786 

Thanks for reporting and yes, we need to fix this. 
I'm closing this because there are more contents on the other issue.
