### ISSUE TITLE
Replace statistics table on the plot with math distribution formula such as N(0, 1)

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/teal.modules.general#9]
Might be problematic as gamma distribution have different set of parameters in usage.

Provenance: 
```
Creator: Polkas
```

**Comment by donyunardi** [comment]
@lcd2yyz 
Can I get your opinion on this?
If not needed, feel free to close this issue.

**Comment by lcd2yyz** [comment]
I don't see a strong need for this. The table in the plot gives the parameter settings for each distribution, with the name of the distribution function itself shown in the legend name as well. It should be pretty clear how to reproduce it outside the module.
I agree to close
